import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f9f9ff",
        foreground: "#111c2d",
        bank: {
          dark: "#080C14",
          surface: "#0F131D",
          card: "#141926",
          cardHover: "#1B2234",
          border: "rgba(255, 255, 255, 0.08)",
          borderGlow: "rgba(59, 130, 246, 0.25)",
          emerald: "#10B981",
          emeraldLight: "#34D399",
          emeraldDim: "rgba(16, 185, 129, 0.12)",
          sapphire: "#3B82F6",
          sapphireLight: "#60A5FA",
          sapphireDark: "#1D4ED8",
          sapphireDim: "rgba(59, 130, 246, 0.15)",
          gold: "#F59E0B",
          goldDim: "rgba(245, 158, 11, 0.12)",
          crimson: "#EF4444",
          crimsonDim: "rgba(239, 68, 68, 0.15)",
          muted: "#94A3B8",
          subtle: "#64748B",
        },
        tertiary: "#5a2e00",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#7c4100",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdcc3",
        "on-background": "#111c2d",
        "surface-tint": "#2156c9",
        "surface-variant": "#d8e3fb",
        "outline-variant": "#c3c6d6",
        "inverse-on-surface": "#ecf1ff",
        "secondary-container": "#c4dcff",
        "surface": "#f9f9ff",
        "inverse-primary": "#b3c5ff",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-tertiary-fixed": "#2f1500",
        primary: "#003289",
        "primary-fixed-dim": "#b3c5ff",
        "surface-container": "#e7eeff",
        "on-tertiary-container": "#ffb273",
        "on-surface": "#111c2d",
        "inverse-surface": "#263143",
        "on-surface-variant": "#434653",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-container-low": "#f0f3ff",
        "on-secondary": "#ffffff",
        "primary-container": "#0047ba",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d2e4ff",
        "on-primary-container": "#aec1ff",
        "surface-dim": "#cfdaf2",
        "on-secondary-fixed-variant": "#314865",
        "surface-container-high": "#dee8ff",
        "secondary-fixed-dim": "#b0c8eb",
        "on-secondary-fixed": "#001c37",
        "surface-container-highest": "#d8e3fb",
        "on-primary-fixed-variant": "#003ea6",
        secondary: "#49607e",
        "on-primary-fixed": "#00174a",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-secondary-container": "#49617f",
        outline: "#737685",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        margin: "1.5rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2.5rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        gutter: "1.25rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "Menlo", "Courier New", "monospace"],
        "financial-numeric": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "label-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-xl": ["IBM Plex Sans", "sans-serif"],
        "headline-xl-mobile": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "financial-numeric": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
        glowSapphire: "0 0 20px -3px rgba(59, 130, 246, 0.4)",
        glowEmerald: "0 0 20px -3px rgba(16, 185, 129, 0.4)",
        card: "0 4px 20px -2px rgba(0, 0, 0, 0.5)",
      },
      animation: {
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 2s linear infinite",
      },
      keyframes: {
        shimmer: {
          from: { backgroundPosition: "0 0" },
          to: { backgroundPosition: "-200% 0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
